### ISSUE TITLE
Can you provide an example？

### ISSUE THREAD

**Issue by 826327700** [aliyigitbireroglu/flutter-cupertino-stackview#1]
I don't know how to use it after read you README.MD , can you provide an example how to organize codes , thanks very much！

**Comment by aliyigitbireroglu** [comment]
You can find the example [here](https://github.com/aliyigitbireroglu/flutter-cupertino-stackview/tree/master/cupertino_stackview/example). If this example is not enough, you can ask to me again👍🏻

**Comment by yehot** [comment]
@826327700
cd exapmle/
flutter create .
then there is iOS and Android example

**Comment by aliyigitbireroglu** [comment]
> @826327700
> cd exapmle/
> flutter create .
> then there is iOS and Android example

That is correct, I didn't upload build folders😃
