### ISSUE TITLE
Child padding top

### ISSUE THREAD

**Issue by dagovalsusa** [aliyigitbireroglu/flutter-cupertino-stackview#2]
Can I set default padding top on a child element?
Thanks

**Comment by aliyigitbireroglu** [comment]
Do you mean the distance between the top of the stacks and the top of the device?

**Comment by dagovalsusa** [comment]
Hello,
No, I mean the distance between the top of the view and it’s contents. 
Seems that each stack view has an empty header

Thanks

**Comment by aliyigitbireroglu** [comment]
I'm sorry, I don't understand what you mean. Can you share an image?

**Comment by dagovalsusa** [comment]
I mean this 
![Schermata 2020-02-24 alle 08 44 15](https://user-images.githubusercontent.com/11755587/75135555-2fa28880-56e2-11ea-8b06-3eb1690eebe9.png)

**Comment by aliyigitbireroglu** [comment]
At the moment, a customisable value is not a part of this package but you can play with the values in "misc.dart" to change that.
