### ISSUE TITLE
Tap on the top of the rear page for getting back leads app to a weird state.

### ISSUE THREAD

**Issue by imaNNeo** [aliyigitbireroglu/flutter-cupertino-stackview#3]
If you swipe the front page down, everything works well, 
but If you press the top of the rear page for back, 
it's going to a weird state, and it lost its functionality.

(I've checked it in your `/example` app).
![image](https://user-images.githubusercontent.com/7009300/83059415-1ad1ea00-a06f-11ea-9735-1b0af296de0c.png)

**Comment by aliyigitbireroglu** [comment]
Thank you for reporting this issue. I will release a fix as soon as possible and let you know too.

**Comment by imaNNeo** [comment]
Thanks!

**Comment by imaNNeo** [comment]
Hey man,
any fix estimation on this issue?

**Comment by aliyigitbireroglu** [comment]
Yes, Monday👍🏻

**Comment by imaNNeo** [comment]
Thanks for your quick respone

**Comment by aliyigitbireroglu** [comment]
Hi again. I am now testing the example application and I can't find any errors besides the wrong layout of the UI due to the misplacement of the widgets. Especially in reference to the issue you've reported, I am a bit confused because "pressing the top of the rear page for back" is not a functionality embedded in this library. You can go back either by pressing the back arrows or by sliding down a page.

**Comment by imaNNeo** [comment]
Hmm, then how can I disable tapping there?

**Comment by aliyigitbireroglu** [comment]
What I meant is by default, tapping there should not do anything. I just published a small update with an Example application that is easier to see and test. Can you try that as well?

**Comment by imaNNeo** [comment]
Where did you publish the update?
Sure, I will check it.

**Comment by aliyigitbireroglu** [comment]
I published it to [pub.dev.](https://pub.dev/packages/cupertino_stackview/versions)

**Comment by imaNNeo** [comment]
It didn't fix,
I checked `1.0.5`

**Comment by aliyigitbireroglu** [comment]
I am kind of confused about this issue because when I press on the top of the rear page, nothing happens as it is not coded to do something. Can I trouble you for a screen recording?

**Comment by imaNNeo** [comment]
Sliding a stack down is working perfectly, however, pressing on the behind stack is not normal behavior and should not be permitted.
Look at this [video](https://streamable.com/tz0gsd) please,
the last touch has happened here which causes the bug:
![Screenshot 2020-06-09 at 1 05 24 PM](https://user-images.githubusercontent.com/7009300/84196079-e9b4d900-aab4-11ea-83d1-fd0b4c7bba44.png)

It is happening in the latest version (1.0.5), on the `/example` project.
Let me know if it is confusing anymore.
Thanks!

**Comment by aliyigitbireroglu** [comment]
Hello! Many apologies for the delay, I finally had some time to return my personal works. After upgrading my Flutter to the latest version, I saw the problem you were having and released a quick fix both on pub.dev and here. Take a look and I hope now it is alright🙂
